#Platform
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_BOARD_PLATFORM := s5pc110
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a8
TARGET_BOOTLOADER_BOARD_NAME := herring
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
# Kernel
BOARD_KERNEL_CMDLINE := console=ttyFIQ0 no_console_suspend
BOARD_PAGE_SIZE := 4096
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --second_offset 0x00f00000
TARGET_KERNEL_CONFIG := crespo_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/crespo
BOARD_CUSTOM_BOOTIMG_MK := device/samsung/crespo/custombootimg.mk
BOARD_CANT_BUILD_RECOVERY_FROM_BOOT_PATCH := true
# Partitions
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_FLASH_BLOCK_SIZE := 4096

# TWRP flags
TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_10x18.h\"
TW_THEME := portrait_mdpi
TW_NO_SCREEN_BLANK := true
DEVICE_RESOLUTION := 480x800
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_HAS_LARGE_FILESYSTEM := true
SP1_NAME := "efs"
SP1_DISPLAY_NAME := "EFS"
SP1_BACKUP_METHOD := files
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/s3c-usbgadget/gadget/lun0/file
